name: "Hello Actions"
description: "Greet action"
author: "Kotli"

inputs:
  MY_NAME:
    description: "Hi everyone"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
